# This workflow performs continuous integration on node 8.x - 14.x, the last of
# which reached end-of-life on 2023-04-30 according to the [release schedule][1]
# published by the [release working group][2].
#
# [1]: https://github.com/nodejs/release/blob/main/schedule.json
# [2]: https://github.com/nodejs/release

name: "Node.js CI (EOL: 2014-07-31)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 0.8.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: export NODE_TLS_REJECT_UNAUTHORIZED=0
    - run: npm conf set registry="http://registry.npmjs.org/"
    - run: npm config set strict-ssl false
    - run: npm cache clean
    - run: cat ~/.npmrc
    - run: npm config list
    - run: npm config list -l
    - run: which npm
    - run: ls /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules
    - run: NODE_TLS_REJECT_UNAUTHORIZED=0 npm install
    - run: npm test
