# This workflow performs continuous integration on node 8.x - 14.x, the last of
# which reached end-of-life on 2023-04-30 according to the [release schedule][1]
# published by the [release working group][2].
#
# [1]: https://github.com/nodejs/release/blob/main/schedule.json
# [2]: https://github.com/nodejs/release

name: "Node.js CI (EOL: 2014-07-31)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 0.8.x ]

# https://github.com/npm/npm/issues/20191
# openssl s_client -showcerts -connect registry.npmjs.org:443
# openssl s_client -connect www.google.com:443 2>/dev/null </dev/null |  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
# openssl s_client -showcerts -connect registry.npmjs.org:443 2>/dev/null </dev/null |  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: export NODE_TLS_REJECT_UNAUTHORIZED=0
    - run: npm conf set registry="http://registry.npmjs.org/"
    - run: npm config set strict-ssl false
    - run: npm cache clean
    - run: cat ~/.npmrc
    - run: npm config list
    - run: npm config list -l
    - run: which npm
    - run: openssl ciphers -v | awk '{print $2}' | sort | uniq
    - run: ls /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules/npm/lib
    - run: ls /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules/npm/node_modules
    - run: ls /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules/npm/node_modules/npmconf
    - run: cat /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules/npm/node_modules/npmconf/config-defs.js
    - run: cp etc/config-defs.js.new /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules/npm/node_modules/npmconf/config-defs.js
    - run: cat /opt/hostedtoolcache/node/0.8.28/x64/lib/node_modules/npm/node_modules/npmconf/config-defs.js
    - run: NODE_TLS_REJECT_UNAUTHORIZED=0 npm install
    - run: npm test
