# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - current
        - 22.x
        - 20.x
        - 18.x
        - 16.x
        - 14.x

    steps:
    - uses: actions/checkout@v4
    - id: setup-node
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - id: node-version
      uses: apexskier/github-semver-parse@v1
      with:
        version: ${{ steps.setup-node.outputs.node-version }}
    - env:
        N_VERSION: ${{steps.setup-node.outputs.node-version}}
      run: echo "$N_VERSION"
    - env:
        N_MAJOR: ${{steps.node-version.outputs.major}}
        N_MINOR: ${{steps.node-version.outputs.minor}}
      run: echo "$N_MAJOR $N_MINOR"
     
    - id: npm-v
      name: Get npm version
      run: echo "version=${npm -v}" >> $GITHUB_OUTPUT
      
    - id: npm-version
      uses: apexskier/github-semver-parse@v1
      with:
        version: ${{ steps.npm-v.outputs.version }}
        
    - env:
        N_MAJOR: ${{steps.npm-version.outputs.major}}
        N_MINOR: ${{steps.npm-version.outputs.minor}}
      run: echo "npm - $N_MAJOR $N_MINOR"
      
    - run: npm ci
      if: matrix.node-version >= '16'
    - run: npm install
      if: matrix.node-version < '16'
    - run: npm test
