# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x, 20.x, 18.x ]
          #- '17'
          #- '17'
          #- '16'
          #- '14'
          #- '12'
          #- '10'
          #- '8'
          #- '6'
          #- '4'
          # - '3' # io.js
          # - '2' # io.js
          # - '1' # io.js
          #- '0.12'
          #- '0.10'
          # - '0.8'

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm install
    - run: npm test
