# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "Node.js CI (EOL: 2023-04-30)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # The package-lock.json use version 3 of file format, which is
        # [incompatible][1] with npm 6.x (distibuted with node 8.x - 14.x) and 5.x
        #
        # [1]: https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion
        node-version: [ 6.x ]
#        node-version: [ 10.x, 8.x, 6.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
