name: Node.js NVM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '0.8.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: dcodeIO/setup-node-nvm@v5
      with:
        node-version: ${{ matrix.node-version }}
        node-mirror: https://nodejs.org/dist
    - run: npm install
    - run: npm test
