name: Node.js NVM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '0.8.x', '0.6.x' ]

    steps:
    - run: sudo apt-get install -y python2.7
    - run: ls /usr/bin/p*
    - run: python --version
    #- run: export PYTHON=/usr/bin/python2.7
    - run: ln -s /usr/bin/python2.7 /usr/bin/python
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: dcodeIO/setup-node-nvm@v5
      with:
        node-version: ${{ matrix.node-version }}
        node-mirror: https://nodejs.org/dist
    - run: sudo apt-get install -y stunnel
    - run: stunnel etc/stunnel.conf
    - run: npm config set registry="http://registry.npmjs.org/"
    - run: npm config set proxy http://localhost:8080
    - run: npm install
    - run: npm test
