# This workflow performs continuous integration on node 8.x - 14.x, the last of
# which reached end-of-life on 2023-04-30 according to the [release schedule][1]
# published by the [release working group][2].
#
# [1]: https://github.com/nodejs/release/blob/main/schedule.json
# [2]: https://github.com/nodejs/release

name: "Stunnel Experiment"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 0.8.x ]
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get install -y stunnel
    - run: stunnel etc/stunnel.conf
    - run: sleep 5
    - run: cat /home/runner/work/passport-http-bearer/passport-http-bearer/stunnel.log
    #- run: ls /var/log
    #- run: cat /home/runner/work/passport-http-bearer/passport-http-bearer/stunnel.log
    #- run: curl http://registry.npmjs.org/passport-strategy --proxy http://127.0.0.1:8086
    - run: curl https://registry.npmjs.org/passport-strategy --proxy https://127.0.0.1:8086
    #- run: npm config set registry="http://registry.npmjs.org/"
    - run: npm config set http-proxy http://localhost:8086
    - run: npm config set https-proxy http://localhost:8086
    - run: npm install
    - run: cat /home/runner/work/passport-http-bearer/passport-http-bearer/stunnel.log
      if: always()
